### ISSUE TITLE
Exporting a document to png crashed for the snap store version.

### ISSUE THREAD

**Issue by aguang-xyz** [aguang-xyz/aurora-editor#20]
**Describe the bug**
For the aurora-editor installed from the snap channel, it crashed while exporting a document to png.

**To peproduce**
1. Install aurora-editor from the snap store: `sudo snap install aurora-editor`
2. Open a markdown document via aurora-editor.
3. Go to file and click `file -> export -> png`

**Expected behaviour**
Show some prompt to select the saving path.

**Screenshots**
![image](https://user-images.githubusercontent.com/46846389/98643943-9cef6a00-2394-11eb-84d8-87aec7ff699f.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Version [18.04]

**Error messages**

```
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
Gtk-Message: 20:32:26.328: GtkDialog mapped without a transient parent. This is discouraged.
tmp-html-path: /run/user/1000/snap.aurora-editor/u0z1ky4xs0q.html
(node:7759) UnhandledPromiseRejectionWarning: Error: spawn ENOTDIR
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at Object.spawn (child_process.js:553:9)
    at BrowserRunner.start (/snap/aurora-editor/46/resources/app.asar/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:79:34)
    at ChromeLauncher.browser [as launch] (/snap/aurora-editor/46/resources/app.asar/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:84:16)
    at exportPng (/snap/aurora-editor/46/resources/app.asar/webpack:/src/main/lib/Commands.js:238:9)
(node:7759) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7759) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by aguang-xyz** [comment]
Seems to be some issue about using puppeteer in electron. Found some helpful comments [here](https://github.com/puppeteer/puppeteer/issues/2134#issuecomment-370024873).

Some potential workaround (not verified yet):

```javascript
const browserFetcher = puppeteer.createBrowserFetcher();
const localChromiums = await browserFetcher.localRevisions();

if(!localChromiums.length) return console.error('Can\'t find installed Chromium');

const { executablePath } = await browserFetcher.revisionInfo(localChromiums[0]);

const browser = await puppeteer.launch({
   executablePath: executablePath
});
```

```javascript
"build": {
    "asar": true,
    "asarUnpack": "node_modules/puppeteer/.local-chromium/**/*"
}
```
